<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell" failures="1" tests="4" name="Test" time="3.115" errors="0" timestamp="2025-03-17T16:01:08 IST">
  <testcase classname="com.XooperAPIFlows.AIJDCreation_APIFlow" name="AIJDwithExcelTestData" time="2.56"/>
  <testcase classname="com.XooperAPIFlows.AIJDCreation_APIFlow" name="AIJDwithExcelTestData" time="0.182"/>
  <testcase classname="com.XooperAPIFlows.AIJDCreation_APIFlow" name="AIJDwithExcelTestData" time="0.151"/>
  <testcase classname="com.XooperAPIFlows.AIJDCreation_APIFlow" name="AIJDwithInvalidExcelTestData" time="0.16">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.lang.RuntimeException but got java.lang.AssertionError: API returned 422 Unprocessable Entity as expected.">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.RuntimeException but got java.lang.AssertionError: API returned 422 Unprocessable Entity as expected.
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.AssertionError: API returned 422 Unprocessable Entity as expected.
at com.XooperAPITest.API_AIJDCreationTest.testAIJDAPI(API_AIJDCreationTest.java:78)
at com.XooperAPIFlows.AIJDCreation_APIFlow.AIJDwithInvalidExcelTestData(AIJDCreation_APIFlow.java:54)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- AIJDwithInvalidExcelTestData -->
</testsuite> <!-- Test -->
